POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Ana Banana",
  "email": "ana2@banana.com"
}
####


POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "1bc07677-2740-4dd7-ad6c-b6c703335c51"
}
####


POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "e76dd1b1-8230-4fa0-980a-29f60e162fea",
  "account_id_to": "5c5d4fad-bd9c-419d-b8b4-442de290eafa",
  "amount": 1
}
